import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Menu from "./_components/Menu"
import {Logo} from "./_components/CoazIcons"
import { FaFacebook } from "react-icons/fa6";
import { IoLogoWhatsapp } from "react-icons/io";
import { MdEmail } from "react-icons/md";
import { GiMailbox } from "react-icons/gi";
import { FaLocationDot } from "react-icons/fa6";
import { FaClock } from "react-icons/fa";


const Nunito = localFont({
    src: [
        {
            path: '../../public/fonts/NunitoSans-ExtraLight.ttf',
            style: 'normal',
            weight: '200'
    },
    {
      path: '../../public/fonts/NunitoSans-ExtraLightItalic.ttf',
      style:'italic',
      weight: '200'
    },
    {
      path: '../../public/fonts/NunitoSans-Light.ttf',
      style:'normal',
      weight: '300'
    },
    {
      path: '../../public/fonts/NunitoSans-LightItalic.ttf',
      style:'italic',
      weight: '300'
    },
    {
      path: '../../public/fonts/NunitoSans-Regular.ttf',
      style:'normal',
      weight: '400'
    },
    {
      path: '../../public/fonts/NunitoSans-Italic.ttf',
      style:'italic',
      weight: '400'
    },
    {
      path: '../../public/fonts/NunitoSans-Medium.ttf',
      style:'normal',
      weight: '500'
    },
    {
      path: '../../public/fonts/NunitoSans-MediumItalic.ttf',
      style:'italic',
      weight: '500'
    },
    {
      path: '../../public/fonts/NunitoSans-SemiBold.ttf',
      style:'normal',
      weight: '600'
    },
    {
      path: '../../public/fonts/NunitoSans-SemiBoldItalic.ttf',
      style:'italic',
      weight: '600'
    },
    {
      path: '../../public/fonts/NunitoSans-Bold.ttf',
      style:'normal',
      weight: '700'
    },
    {
      path: '../../public/fonts/NunitoSans-BoldItalic.ttf',
      style:'italic',
      weight: '700'
    },
    {
      path: '../../public/fonts/NunitoSans-ExtraBold.ttf',
      style:'normal',
      weight: '800'
    },
    {
      path: '../../public/fonts/NunitoSans-ExtraBoldItalic.ttf',
      style:'italic',
      weight: '800'
    },
    {
      path: '../../public/fonts/NunitoSans-Black.ttf',
      style:'normal',
      weight: '900'
    },
    {
      path: '../../public/fonts/NunitoSans-BlackItalic.ttf',
      style:'italic',
      weight: '900'
    }
  ],
  variable: '--font-nunito'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Nunito.variable} antialiased`}
      >
        <header className="h-fit">
          <Menu/>
        </header>
        {children}
        <footer className="px-8 py-10 bg-[rgb(0,175,240)]">
          <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8">


            <div className="flex flex-col items-center md:items-start">
              <div className="w-50 h-50 bg-white rounded-full mb-4 flex items-center justify-center font-bold text-black">
                <Logo fill="rgb(0,175,240)"/>
              </div>
              <p className="text-center md:text-left">
              </p>
            </div>


            <div>
              <h3 className="font-semibold mb-4">CONTACT US</h3>
              <ul className="space-y-2">
                  <li className="flex items-center gap-2">
                    <MdEmail /> info@coaz.com
                </li>
                <li className="flex items-center gap-2">
                    <IoLogoWhatsapp /> +260761234390
                </li>
                <li className="flex items-center gap-2">
                    <FaFacebook /> Clinical Officers Association Of Zambia
                </li>
                <li className="flex items-center gap-2">
                    <GiMailbox /> P.O Box 12345
                </li>
              </ul>
            </div>


            <div>
              <h3 className="font-semibold mb-4">LOCATION</h3>

                  <li className="flex items-center gap-2">
                      <FaLocationDot /> Kapwayambale Rd, Obama
                  </li>


              </div>



            <div>
              <h3 className="font-semibold mb-4">WORK HOURS</h3>

              <ul>
                  <li className="flex items-center gap-2">
                      <FaClock /> Week Days: 08:00 - 17:00
                  </li>

                  <li className="flex items-center gap-2">
                      <FaClock /> Weekends:  08:00 - 12:00
                  </li>
              </ul>
              </div>

            </div>

        </footer>
      </body>
    </html>
  );
}

